### ISSUE TITLE
RuntimeWarning: coroutine 'Bot.send_photo' was never awaited

### ISSUE THREAD

**Issue by Dorlas** [EIDiamond/grafana_panel_image_downloader#1]
Thank you very much for the program!

That's what I've been looking for the last week.

Started testing - saving panels to PNG works great!

BUT, when I try to send to Telegramm, I get an error.

**Comment by EIDiamond** [comment]
Hi @Dorlas, thank you for feedback. 

Please test the following version 'python-telegram-bot' package. 
python-telegram-bot==13.15

Actually, I used this version and forgot to set it in the requrements.txt file. 
Thank you for pointing it.

**Comment by EIDiamond** [comment]
[requirements.txt](requirements.txt) was [updated](https://github.com/EIDiamond/grafana_image_downloader/commit/f799050c24348b3ea5a9f4ec12b59bb311b28b01)

**Comment by Dorlas** [comment]
Wow - big thanks!!! All works very well now!
