### ISSUE TITLE
Add more information about grafana-image-renderer installation HOW-TO

### ISSUE THREAD

**Issue by Dorlas** [EIDiamond/grafana_panel_image_downloader#4]
I hope the following information can help someone!

When I installed the plugin grafana-image-renderer (with command **grafana-cli plugins install grafana-image-renderer**) the program don't work well.
I had to figure out why - the answer was in the grafana log (/var/log/grafana/grafana.log).
After several tries I found what libraries are missing:

<code>
libnss3.so
libatk-1.0.so.0
libatk-bridge-2.0.so.0
libcups.so.2
libxkbcommon.so.0
libXcomposite.so.1
libXdamage.so.1
libXfixes.so.3
libXrandr.so.2
libgbm.so.1
libpango-1.0.so.0
libasound.so.2
</code>

In your system the best way - see all missing libraries by command:
**ldd /var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome**

And next more and more apt/yum search && apt/yum install <libraries>.

**Comment by EIDiamond** [comment]
Thank you again for sharing. 

I've added [documentation](https://github.com/EIDiamond/grafana_image_downloader/blob/main/HOW_TO_grafana_installations.md) for such cases. 

Also I described my case - k8s and helm. (it's working pretty well)
